### ISSUE TITLE
Archive build action or custom options parameter

### ISSUE THREAD

**Issue by lkravchuk** [Redth/Cake.XCode#1]
Hi Jonathan,
can you please add an additional buildaction for the app archives creation - `archive` or at least some custom property in `XCodeBuildSettings` data model to make it possible to define custom actions and/or build options by user. - [xcodebuild docs](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/xcodebuild.1.html)
It would be really useful.
Thank you.

**Comment by Redth** [comment]
Done.
