### ISSUE TITLE
Update Cake.XCode to target Cake v1.0.0

### ISSUE THREAD

**Issue by nils-a** [Redth/Cake.XCode#15]
https://cakebuild.net/blog/2021/02/cake-v1.0.0-released

## Expected Behavior

Cake.XCode should be compatible with the current version of Cake.

## Current Behavior

Cake.XCode is not compatible with the current version of Cake, see #14 

## Possible Solution

Update Cake references to target Cake 1.0.0

## Steps to Reproduce (for bugs)
see #14

**Comment by jingliancui** [comment]
Awesome, Is it can be getting release ?

**Comment by augustoproiete** [comment]
Hey @jingliancui yes, I'll release a new version shortly.

**Comment by jingliancui** [comment]
@augustoproiete Nice! thanks.

**Comment by jingliancui** [comment]
Hello @augustoproiete , is there any progress about that? It's seem like it still 4.2.0 now.

**Comment by augustoproiete** [comment]
@jingliancui Cake.XCode v5.0.0 has just been published to nuget.org

**Comment by jingliancui** [comment]
@augustoproiete Awesome, Thank you very much again.
